crds:
  install: true
  keep: true

image:
  tag: "latest"
  pullPolicy: ""

telemetry:
  enabled: true

controllerImage: ghcr.io/kelos-dev/kelos-controller
ghproxy:
  image: ghcr.io/kelos-dev/ghproxy
  allowedUpstreams: "https://api.github.com"
claudeCodeImage: ghcr.io/kelos-dev/claude-code
codexImage: ghcr.io/kelos-dev/codex
geminiImage: ghcr.io/kelos-dev/gemini
opencodeImage: ghcr.io/kelos-dev/opencode
cursorImage: ghcr.io/kelos-dev/cursor
spawner:
  image: ghcr.io/kelos-dev/kelos-spawner
  resources:
    requests: ""
    limits: ""
tokenRefresher:
  image: ghcr.io/kelos-dev/kelos-token-refresher
  resources:
    requests: ""
    limits: ""
controller:
  resources:
    requests: {}
    limits: {}
