---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kelos-controller
  namespace: kelos-system
{{- if .Values.webhookServer.sources.github.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kelos-webhook
  namespace: {{ .Release.Namespace }}
{{- end }}
